/* Esta lista podría ser reemplazada por la respuesta de un backend */
const listaClientes = [
  {
    id: 1,
    nombre: "Brandon",
    apellido: "Gutierrez",
    //  segundo_nombre: "Gabriel",
    //  segundo_apellido: "Camacaro",
    cedula: 30,
    deuda: 40,
    tipoDeCliente: "hola",
  },
  {
    id: 2,
    nombre: "Pepe",
    apellido: "Gutierrez",
    // segundo_nombre: "luis",
    // segundo_apellido: "Camacaro",
    cedula: 30,
    deuda: 40,
    tipoDeCliente: "hola",
    //telefono: 42,
  },
  {
    id: 3,
    nombre: "genesis",
    apellido: "Gutierrez",
    // segundo_nombre: "Gabriela",
    // segundo_apellido: "Camacaro",
    cedula: 30,
    deuda: 40,
    tipoDeCliente: "hola",
    //telefono: 43,
  },
  {
    id: 4,
    nombre: "Miguel",
    apellido: "Gutierrez",
    // segundo_nombre: "Juan",
    // segundo_apellido: "Camacaro",
    cedula: 30,
    deuda: 40,
    tipoDeCliente: "hola",
    // telefono: 44,
  },
  {
    id: 5,
    nombre: "Brandon",
    apellido: "Gutierrez",
    //segundo_nombre: "Gabriel",
    //segundo_apellido: "Camacaro",
    cedula: 30,
    deuda: 40,
    tipoDeCliente: "hola",
    // telefono: 45,
  },
  {
    id: 6,
    nombre: "Brandon",
    apellido: "Gutierrez",
    // segundo_nombre: "Gabriel",
    // segundo_apellido: "Camacaro",
    cedula: 30,
    deuda: 40,
    tipoDeCliente: "hola",
    //telefono: 46,
  },
  {
    id: 7,
    nombre: "Brandon",
    apellido: "Gutierrez",
    // segundo_nombre: "Gabriel",
    // segundo_apellido: "Camacaro",
    cedula: 30,
    deuda: 40,
    tipoDeCliente: "hola",
    //telefono: 46,
  },
  {
    id: 8,
    nombre: "Brandon",
    apellido: "Gutierrez",
    // segundo_nombre: "Gabriel",
    // segundo_apellido: "Camacaro",
    cedula: 30,
    deuda: 40,
    tipoDeCliente: "hola",
    //telefono: 46,
  },
];
